sudo: false

language: node_js
node_js:
  - 10

env:
  - CI=true
  - CI_BUILD=true
  - CI_STORYBOOK=true

script:
  -  if [ "${CI}" = "true" ]; then npm run test -- --coverage; fi
  -  if [ "${CI_BUILD}" = "true" ]; then npm run build; fi
  -  if [ "${CI_STORYBOOK}" = "true" ]; then npm run build-storybook; fi

deploy:
  provider: gcs
  access_key_id: GOOGSML5SDHJDCVE2HSOZZLX
  secret_access_key:
    secure: 3rkxt4UsIx9lCdhj1o/4zK/190EYkmU1HuCXrs4vfS2PGVwRXPJ+GwvoLWV9s/z1idXaTxvMPuQao3CkdJUhSrRUG0zkplk1bd2uBoCtbnvCikqa/hGxzuY+yaX40KXdtbr7NbY4rNO8BWJrfDKGa1VttLhevnNe4v6ToTULTAaSm67+Zr+zAiLE958HfBW0GqqLza0YLP1s6tArAYvzaEjTcVimEbwdN169jnwWRi7z3qFdrt6bt8oq/+M46IGxi1t/CxzdY5hcICwzjOMjoxM7uHpcR4DLOskGYdnHapLkX1fNDHdYcmueKEWi0HPtclegLzzVjNovw/98YQke0txgza7AgFVeka1eM9qg4vel7V+UOiu7kM/BGZtqdUWMpKgtm7EzGQi/zQ4ExuG4qXRoS8kVM1nCAa4nn+c7vFOi3KSqM0hqqjoxuIKt1PBn42mHQ1yzgCCcgrWh++FcZ+YhP2m7eYVvDjL1yQa4XabT/JktE/ScrJ/U997u25bEa6FYNkYklPR7Dp4Z6/uWWFTXzFCeeSudKuHevPoVbHJAEz6KcHqYi8oalHzMXLZMhU/tdSgJ1e4vHMUr7wcBqhuE9fUWMrhbDFFl5uGbuC8zrAEHk3JdlRsKvP9+7R0MGMte9Z7FFfzTAYbvGVY/DPLtg960wmdAel4lZtGkjb0=
  bucket: static.gieffektivt.no
  skip_cleanup: true
  acl: public-read
  local-dir: build
  on:
    repo: stiftelsen-effekt/effekt-admin
