steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config -f .gitmodules submodule.histoslider.url https://source.developers.google.com/p/hidden-display-243419/r/github_fellmirr_histoslider
    git submodule init
    git submodule update
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  env: ['CI=true']
  args: ['run', 'test']
- name: 'gcr.io/cloud-builders/npm'
  env: ['CI=true']
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'build/*', 'gs://static.gieffektivt.no/']